-- AlterTable: Add managerId field to StaffMember for team assignment
ALTER TABLE "StaffMember" ADD COLUMN IF NOT EXISTS "managerId" TEXT;

-- AddForeignKey: Create self-referential relation for manager-team mapping
-- Note: This creates a foreign key constraint
-- The constraint name will be auto-generated by Prisma

-- Add index for better query performance
CREATE INDEX IF NOT EXISTS "StaffMember_managerId_idx" ON "StaffMember"("managerId");

-- Add comment
COMMENT ON COLUMN "StaffMember"."managerId" IS 'Staff ID of the manager (for team assignment)';

