/**
 * Comprehensive Role-Based User Seed Data
 * Ministry of Fisheries and Aquaculture Development (MoFAD)
 * 
 * Complete organizational structure with all directorates, units, sub-units,
 * and role-based users with full details.
 */

export interface RoleBasedUserSeed {
  userId: string
  name: string
  firstName: string
  lastName: string
  email: string
  phone: string
  role: string
  staffId: string
  directorate?: string
  unit?: string
  subUnit?: string
  reportsTo?: string // userId of immediate supervisor or HoD
  functional?: boolean // true for HR roles
  position: string
  grade: string
  level: string
  rank?: string
  step?: string
  department: string
  dutyStation?: string
  joinDate: Date
}

export const roleBasedUsersSeed: RoleBasedUserSeed[] = [
  // -------------------
  // Top-Level
  // -------------------
  {
    userId: 'cd-001',
    name: 'Chief Director',
    firstName: 'Kwame',
    lastName: 'Asante',
    email: 'chiefdirector@mofa.gov.gh',
    phone: '+233241000001',
    role: 'CHIEF_DIRECTOR',
    staffId: 'MoFA-CD-001',
    position: 'Chief Director',
    grade: 'G12',
    level: 'Executive',
    rank: 'Chief Director',
    step: 'Step 1',
    department: 'Office of the Chief Director',
    dutyStation: 'HQ',
    joinDate: new Date('2010-01-15'),
  },

  // ===================
  // CORE DIRECTORATES
  // ===================

  // -------- PPBME DIRECTORATE --------
  {
    userId: 'dir-ppbme',
    name: 'Director PPBME',
    firstName: 'Ama',
    lastName: 'Mensah',
    email: 'director.ppbme@mofa.gov.gh',
    phone: '+233241000002',
    role: 'DIRECTOR',
    staffId: 'MoFA-DIR-PPBME',
    directorate: 'PPBME',
    reportsTo: 'cd-001',
    position: 'Director',
    grade: 'G10',
    level: 'Executive',
    rank: 'Director',
    step: 'Step 5',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2012-03-20'),
  },
  {
    userId: 'hr-ppbme-01',
    name: 'HR Officer PPBME 1',
    firstName: 'Kofi',
    lastName: 'Boateng',
    email: 'hr.ppbme01@mofa.gov.gh',
    phone: '+233241000003',
    role: 'HR_OFFICER',
    staffId: 'MoFA-HR-PPBME-01',
    directorate: 'PPBME',
    functional: true,
    position: 'HR Officer',
    grade: 'G6',
    level: 'Middle',
    rank: 'Principal Officer',
    step: 'Step 2',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2018-06-10'),
  },

  // PPBME Units
  // 1. Policy Coordination Unit
  {
    userId: 'uh-ppbme-policy',
    name: 'Unit Head Policy Coordination',
    firstName: 'Yaa',
    lastName: 'Osei',
    email: 'unithead.policy@mofa.gov.gh',
    phone: '+233241000004',
    role: 'UNIT_HEAD',
    staffId: 'MoFA-UH-PPBME-POLICY',
    unit: 'Policy Coordination Unit',
    directorate: 'PPBME',
    reportsTo: 'dir-ppbme',
    position: 'Unit Head',
    grade: 'G8',
    level: 'Senior',
    rank: 'Principal Officer',
    step: 'Step 4',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2015-08-15'),
  },
  {
    userId: 'sup-ppbme-policy-01',
    name: 'Supervisor Policy Coordination 1',
    firstName: 'Emmanuel',
    lastName: 'Darko',
    email: 'supervisor.policy01@mofa.gov.gh',
    phone: '+233241000005',
    role: 'SUPERVISOR',
    staffId: 'MoFA-SUP-PPBME-POLICY-01',
    unit: 'Policy Coordination Unit',
    directorate: 'PPBME',
    reportsTo: 'uh-ppbme-policy',
    position: 'Senior Policy Analyst',
    grade: 'G7',
    level: 'Senior',
    rank: 'Senior Officer',
    step: 'Step 3',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2017-02-01'),
  },
  {
    userId: 'emp-ppbme-policy-01',
    name: 'Employee Policy Coordination 1',
    firstName: 'Akosua',
    lastName: 'Adjei',
    email: 'employee.policy01@mofa.gov.gh',
    phone: '+233241000006',
    role: 'EMPLOYEE',
    staffId: 'MoFA-EMP-PPBME-POLICY-01',
    unit: 'Policy Coordination Unit',
    directorate: 'PPBME',
    reportsTo: 'sup-ppbme-policy-01',
    position: 'Policy Analyst',
    grade: 'G5',
    level: 'Junior',
    rank: 'Senior Officer',
    step: 'Step 1',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2020-01-10'),
  },

  // 2. Planning & Budgeting Unit
  {
    userId: 'uh-ppbme-pb',
    name: 'Unit Head Planning & Budgeting',
    firstName: 'Kwabena',
    lastName: 'Amoah',
    email: 'unithead.planning@mofa.gov.gh',
    phone: '+233241000007',
    role: 'UNIT_HEAD',
    staffId: 'MoFA-UH-PPBME-PB',
    unit: 'Planning & Budgeting Unit',
    directorate: 'PPBME',
    reportsTo: 'dir-ppbme',
    position: 'Unit Head',
    grade: 'G8',
    level: 'Senior',
    rank: 'Principal Officer',
    step: 'Step 4',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2014-11-20'),
  },
  {
    userId: 'sup-ppbme-pb-01',
    name: 'Supervisor Planning & Budgeting 1',
    firstName: 'Efua',
    lastName: 'Tetteh',
    email: 'supervisor.planning01@mofa.gov.gh',
    phone: '+233241000008',
    role: 'SUPERVISOR',
    staffId: 'MoFA-SUP-PPBME-PB-01',
    unit: 'Planning & Budgeting Unit',
    directorate: 'PPBME',
    reportsTo: 'uh-ppbme-pb',
    position: 'Senior Planning Officer',
    grade: 'G7',
    level: 'Senior',
    rank: 'Senior Officer',
    step: 'Step 3',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2016-05-15'),
  },
  {
    userId: 'emp-ppbme-pb-01',
    name: 'Employee Planning & Budgeting 1',
    firstName: 'Nana',
    lastName: 'Owusu',
    email: 'employee.planning01@mofa.gov.gh',
    phone: '+233241000009',
    role: 'EMPLOYEE',
    staffId: 'MoFA-EMP-PPBME-PB-01',
    unit: 'Planning & Budgeting Unit',
    directorate: 'PPBME',
    reportsTo: 'sup-ppbme-pb-01',
    position: 'Planning Officer',
    grade: 'G5',
    level: 'Junior',
    rank: 'Senior Officer',
    step: 'Step 1',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2021-03-01'),
  },

  // 3. Monitoring & Evaluation Unit
  {
    userId: 'uh-ppbme-me',
    name: 'Unit Head Monitoring & Evaluation',
    firstName: 'Adjoa',
    lastName: 'Asiedu',
    email: 'unithead.monitoring@mofa.gov.gh',
    phone: '+233241000010',
    role: 'UNIT_HEAD',
    staffId: 'MoFA-UH-PPBME-ME',
    unit: 'Monitoring & Evaluation Unit',
    directorate: 'PPBME',
    reportsTo: 'dir-ppbme',
    position: 'Unit Head',
    grade: 'G8',
    level: 'Senior',
    rank: 'Principal Officer',
    step: 'Step 4',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2013-09-10'),
  },
  {
    userId: 'sup-ppbme-me-01',
    name: 'Supervisor Monitoring & Evaluation 1',
    firstName: 'Kojo',
    lastName: 'Mensah',
    email: 'supervisor.monitoring01@mofa.gov.gh',
    phone: '+233241000011',
    role: 'SUPERVISOR',
    staffId: 'MoFA-SUP-PPBME-ME-01',
    unit: 'Monitoring & Evaluation Unit',
    directorate: 'PPBME',
    reportsTo: 'uh-ppbme-me',
    position: 'Senior M&E Officer',
    grade: 'G7',
    level: 'Senior',
    rank: 'Senior Officer',
    step: 'Step 3',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2018-07-20'),
  },
  {
    userId: 'emp-ppbme-me-01',
    name: 'Employee Monitoring & Evaluation 1',
    firstName: 'Maame',
    lastName: 'Frimpong',
    email: 'employee.monitoring01@mofa.gov.gh',
    phone: '+233241000012',
    role: 'EMPLOYEE',
    staffId: 'MoFA-EMP-PPBME-ME-01',
    unit: 'Monitoring & Evaluation Unit',
    directorate: 'PPBME',
    reportsTo: 'sup-ppbme-me-01',
    position: 'M&E Officer',
    grade: 'G5',
    level: 'Junior',
    rank: 'Senior Officer',
    step: 'Step 1',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2022-01-15'),
  },

  // 4. Fisheries Management & Aquaculture Development Unit
  {
    userId: 'uh-ppbme-fma',
    name: 'Unit Head Fisheries Management & Aquaculture',
    firstName: 'Yaw',
    lastName: 'Bonsu',
    email: 'unithead.fisheries@mofa.gov.gh',
    phone: '+233241000013',
    role: 'UNIT_HEAD',
    staffId: 'MoFA-UH-PPBME-FMA',
    unit: 'Fisheries Management & Aquaculture Development Unit',
    directorate: 'PPBME',
    reportsTo: 'dir-ppbme',
    position: 'Unit Head',
    grade: 'G8',
    level: 'Senior',
    rank: 'Principal Officer',
    step: 'Step 4',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2011-04-05'),
  },

  // Sub-Units
  // Culture & Capture Fisheries Sub-Unit
  {
    userId: 'subuh-ppbme-ccf',
    name: 'Sub-Unit Head Culture & Capture Fisheries',
    firstName: 'Aba',
    lastName: 'Kwarteng',
    email: 'subunithead.culture@mofa.gov.gh',
    phone: '+233241000014',
    role: 'UNIT_HEAD',
    staffId: 'MoFA-SUBUH-PPBME-CCF',
    subUnit: 'Culture & Capture Fisheries Sub-Unit',
    unit: 'Fisheries Management & Aquaculture Development Unit',
    directorate: 'PPBME',
    reportsTo: 'uh-ppbme-fma',
    position: 'Sub-Unit Head',
    grade: 'G7',
    level: 'Senior',
    rank: 'Senior Officer',
    step: 'Step 3',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2016-10-12'),
  },
  {
    userId: 'sup-ppbme-ccf-01',
    name: 'Supervisor Culture & Capture Fisheries 1',
    firstName: 'Kweku',
    lastName: 'Agyeman',
    email: 'supervisor.culture01@mofa.gov.gh',
    phone: '+233241000015',
    role: 'SUPERVISOR',
    staffId: 'MoFA-SUP-PPBME-CCF-01',
    subUnit: 'Culture & Capture Fisheries Sub-Unit',
    unit: 'Fisheries Management & Aquaculture Development Unit',
    directorate: 'PPBME',
    reportsTo: 'subuh-ppbme-ccf',
    position: 'Senior Fisheries Officer',
    grade: 'G6',
    level: 'Middle',
    rank: 'Principal Officer',
    step: 'Step 2',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2019-02-18'),
  },
  {
    userId: 'emp-ppbme-ccf-01',
    name: 'Employee Culture & Capture Fisheries 1',
    firstName: 'Ama',
    lastName: 'Gyasi',
    email: 'employee.culture01@mofa.gov.gh',
    phone: '+233241000016',
    role: 'EMPLOYEE',
    staffId: 'MoFA-EMP-PPBME-CCF-01',
    subUnit: 'Culture & Capture Fisheries Sub-Unit',
    unit: 'Fisheries Management & Aquaculture Development Unit',
    directorate: 'PPBME',
    reportsTo: 'sup-ppbme-ccf-01',
    position: 'Fisheries Officer',
    grade: 'G5',
    level: 'Junior',
    rank: 'Senior Officer',
    step: 'Step 1',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2021-08-20'),
  },

  // Post-Harvest & Marketing Sub-Unit
  {
    userId: 'subuh-ppbme-phm',
    name: 'Sub-Unit Head Post-Harvest & Marketing',
    firstName: 'Fiifi',
    lastName: 'Ofori',
    email: 'subunithead.postharvest@mofa.gov.gh',
    phone: '+233241000017',
    role: 'UNIT_HEAD',
    staffId: 'MoFA-SUBUH-PPBME-PHM',
    subUnit: 'Post-Harvest & Marketing Sub-Unit',
    unit: 'Fisheries Management & Aquaculture Development Unit',
    directorate: 'PPBME',
    reportsTo: 'uh-ppbme-fma',
    position: 'Sub-Unit Head',
    grade: 'G7',
    level: 'Senior',
    rank: 'Senior Officer',
    step: 'Step 3',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2017-06-25'),
  },
  {
    userId: 'sup-ppbme-phm-01',
    name: 'Supervisor Post-Harvest & Marketing 1',
    firstName: 'Esi',
    lastName: 'Danso',
    email: 'supervisor.postharvest01@mofa.gov.gh',
    phone: '+233241000018',
    role: 'SUPERVISOR',
    staffId: 'MoFA-SUP-PPBME-PHM-01',
    subUnit: 'Post-Harvest & Marketing Sub-Unit',
    unit: 'Fisheries Management & Aquaculture Development Unit',
    directorate: 'PPBME',
    reportsTo: 'subuh-ppbme-phm',
    position: 'Senior Marketing Officer',
    grade: 'G6',
    level: 'Middle',
    rank: 'Principal Officer',
    step: 'Step 2',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2020-04-10'),
  },
  {
    userId: 'emp-ppbme-phm-01',
    name: 'Employee Post-Harvest & Marketing 1',
    firstName: 'Kofi',
    lastName: 'Sarpong',
    email: 'employee.postharvest01@mofa.gov.gh',
    phone: '+233241000019',
    role: 'EMPLOYEE',
    staffId: 'MoFA-EMP-PPBME-PHM-01',
    subUnit: 'Post-Harvest & Marketing Sub-Unit',
    unit: 'Fisheries Management & Aquaculture Development Unit',
    directorate: 'PPBME',
    reportsTo: 'sup-ppbme-phm-01',
    position: 'Marketing Officer',
    grade: 'G5',
    level: 'Junior',
    rank: 'Senior Officer',
    step: 'Step 1',
    department: 'Policy, Planning, Budgeting, Monitoring & Evaluation Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2022-09-05'),
  },

  // ===================
  // HRMD Directorate
  // ===================
  {
    userId: 'dir-hrmd',
    name: 'HR Director',
    firstName: 'Patience',
    lastName: 'Amoako',
    email: 'director.hrmd@mofa.gov.gh',
    phone: '+233241000020',
    role: 'HR_DIRECTOR',
    staffId: 'MoFA-DIR-HRMD',
    directorate: 'HRMD',
    functional: true,
    reportsTo: 'cd-001',
    position: 'HR Director',
    grade: 'G10',
    level: 'Executive',
    rank: 'Director',
    step: 'Step 5',
    department: 'Human Resource Management Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2013-01-20'),
  },
  {
    userId: 'hr-hrmd-01',
    name: 'HR Officer HRMD 1',
    firstName: 'Samuel',
    lastName: 'Tetteh',
    email: 'hr.hrmd01@mofa.gov.gh',
    phone: '+233241000021',
    role: 'HR_OFFICER',
    staffId: 'MoFA-HR-HRMD-01',
    directorate: 'HRMD',
    functional: true,
    reportsTo: 'dir-hrmd',
    position: 'HR Officer',
    grade: 'G6',
    level: 'Middle',
    rank: 'Principal Officer',
    step: 'Step 2',
    department: 'Human Resource Management Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2019-05-15'),
  },
  {
    userId: 'hr-hrmd-02',
    name: 'HR Officer HRMD 2',
    firstName: 'Gifty',
    lastName: 'Asante',
    email: 'hr.hrmd02@mofa.gov.gh',
    phone: '+233241000022',
    role: 'HR_OFFICER',
    staffId: 'MoFA-HR-HRMD-02',
    directorate: 'HRMD',
    functional: true,
    reportsTo: 'dir-hrmd',
    position: 'HR Officer',
    grade: 'G6',
    level: 'Middle',
    rank: 'Principal Officer',
    step: 'Step 2',
    department: 'Human Resource Management Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2020-08-20'),
  },

  // ===================
  // Independent Supporting Units
  // ===================
  {
    userId: 'iau-001',
    name: 'Head Internal Audit Unit',
    firstName: 'Daniel',
    lastName: 'Appiah',
    email: 'head.audit@mofa.gov.gh',
    phone: '+233241000023',
    role: 'HEAD_OF_INDEPENDENT_UNIT',
    staffId: 'MoFA-IAU-001',
    unit: 'Internal Audit Unit',
    reportsTo: 'cd-001',
    position: 'Head of Internal Audit',
    grade: 'G9',
    level: 'Senior',
    rank: 'Principal Officer',
    step: 'Step 4',
    department: 'Internal Audit Unit',
    dutyStation: 'HQ',
    joinDate: new Date('2014-03-10'),
  },
  {
    userId: 'legal-001',
    name: 'Head Legal Unit',
    firstName: 'Cynthia',
    lastName: 'Owusu',
    email: 'head.legal@mofa.gov.gh',
    phone: '+233241000024',
    role: 'HEAD_OF_INDEPENDENT_UNIT',
    staffId: 'MoFA-LEGAL-001',
    unit: 'Legal Unit',
    reportsTo: 'cd-001',
    position: 'Head of Legal',
    grade: 'G9',
    level: 'Senior',
    rank: 'Principal Officer',
    step: 'Step 4',
    department: 'Legal Unit',
    dutyStation: 'HQ',
    joinDate: new Date('2015-07-18'),
  },
  {
    userId: 'pr-001',
    name: 'Head Public Relations / Communications Unit',
    firstName: 'Michael',
    lastName: 'Bonsu',
    email: 'head.pr@mofa.gov.gh',
    phone: '+233241000025',
    role: 'HEAD_OF_INDEPENDENT_UNIT',
    staffId: 'MoFA-PR-001',
    unit: 'Public Relations / Communications Unit',
    reportsTo: 'cd-001',
    position: 'Head of Public Relations',
    grade: 'G9',
    level: 'Senior',
    rank: 'Principal Officer',
    step: 'Step 4',
    department: 'Public Relations / Communications Unit',
    dutyStation: 'HQ',
    joinDate: new Date('2016-02-22'),
  },
  {
    userId: 'rti-001',
    name: 'Head RTI Unit',
    firstName: 'Ruth',
    lastName: 'Mensah',
    email: 'head.rti@mofa.gov.gh',
    phone: '+233241000026',
    role: 'HEAD_OF_INDEPENDENT_UNIT',
    staffId: 'MoFA-RTI-001',
    unit: 'Right to Information (RTI) Unit',
    reportsTo: 'cd-001',
    position: 'Head of RTI',
    grade: 'G9',
    level: 'Senior',
    rank: 'Principal Officer',
    step: 'Step 4',
    department: 'Right to Information (RTI) Unit',
    dutyStation: 'HQ',
    joinDate: new Date('2017-11-05'),
  },
  {
    userId: 'csu-001',
    name: 'Head Client Service Unit',
    firstName: 'Joseph',
    lastName: 'Agyeman',
    email: 'head.clientservice@mofa.gov.gh',
    phone: '+233241000027',
    role: 'HEAD_OF_INDEPENDENT_UNIT',
    staffId: 'MoFA-CSU-001',
    unit: 'Client Service Unit',
    reportsTo: 'cd-001',
    position: 'Head of Client Service',
    grade: 'G9',
    level: 'Senior',
    rank: 'Principal Officer',
    step: 'Step 4',
    department: 'Client Service Unit',
    dutyStation: 'HQ',
    joinDate: new Date('2018-04-12'),
  },

  // ===================
  // RSIMD Directorate (Research, Statistics & Information Management)
  // ===================
  {
    userId: 'dir-rsimd',
    name: 'Director RSIMD',
    firstName: 'Felix',
    lastName: 'Amoah',
    email: 'director.rsimd@mofa.gov.gh',
    phone: '+233241000028',
    role: 'DIRECTOR',
    staffId: 'MoFA-DIR-RSIMD',
    directorate: 'RSIMD',
    reportsTo: 'cd-001',
    position: 'Director',
    grade: 'G10',
    level: 'Executive',
    rank: 'Director',
    step: 'Step 5',
    department: 'Research, Statistics & Information Management Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2012-08-15'),
  },
  {
    userId: 'hr-rsimd-01',
    name: 'HR Officer RSIMD 1',
    firstName: 'Esther',
    lastName: 'Darko',
    email: 'hr.rsimd01@mofa.gov.gh',
    phone: '+233241000029',
    role: 'HR_OFFICER',
    staffId: 'MoFA-HR-RSIMD-01',
    directorate: 'RSIMD',
    functional: true,
    reportsTo: 'dir-rsimd',
    position: 'HR Officer',
    grade: 'G6',
    level: 'Middle',
    rank: 'Principal Officer',
    step: 'Step 2',
    department: 'Research, Statistics & Information Management Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2020-01-10'),
  },

  // RSIMD Units
  {
    userId: 'uh-rsimd-research',
    name: 'Unit Head Research',
    firstName: 'Dr. Comfort',
    lastName: 'Asiedu',
    email: 'unithead.research@mofa.gov.gh',
    phone: '+233241000030',
    role: 'UNIT_HEAD',
    staffId: 'MoFA-UH-RSIMD-RESEARCH',
    unit: 'Research Unit',
    directorate: 'RSIMD',
    reportsTo: 'dir-rsimd',
    position: 'Unit Head',
    grade: 'G8',
    level: 'Senior',
    rank: 'Principal Officer',
    step: 'Step 4',
    department: 'Research, Statistics & Information Management Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2014-06-20'),
  },
  {
    userId: 'sup-rsimd-research-01',
    name: 'Supervisor Research 1',
    firstName: 'Dr. Isaac',
    lastName: 'Osei',
    email: 'supervisor.research01@mofa.gov.gh',
    phone: '+233241000031',
    role: 'SUPERVISOR',
    staffId: 'MoFA-SUP-RSIMD-RESEARCH-01',
    unit: 'Research Unit',
    directorate: 'RSIMD',
    reportsTo: 'uh-rsimd-research',
    position: 'Senior Research Officer',
    grade: 'G7',
    level: 'Senior',
    rank: 'Senior Officer',
    step: 'Step 3',
    department: 'Research, Statistics & Information Management Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2017-03-15'),
  },
  {
    userId: 'emp-rsimd-research-01',
    name: 'Employee Research 1',
    firstName: 'Victoria',
    lastName: 'Agyeman',
    email: 'employee.research01@mofa.gov.gh',
    phone: '+233241000032',
    role: 'EMPLOYEE',
    staffId: 'MoFA-EMP-RSIMD-RESEARCH-01',
    unit: 'Research Unit',
    directorate: 'RSIMD',
    reportsTo: 'sup-rsimd-research-01',
    position: 'Research Officer',
    grade: 'G5',
    level: 'Junior',
    rank: 'Senior Officer',
    step: 'Step 1',
    department: 'Research, Statistics & Information Management Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2021-05-20'),
  },

  // ===================
  // F&A Directorate (Finance & Administration)
  // ===================
  {
    userId: 'dir-fa',
    name: 'Director F&A',
    firstName: 'Mary',
    lastName: 'Boateng',
    email: 'director.fa@mofa.gov.gh',
    phone: '+233241000033',
    role: 'DIRECTOR',
    staffId: 'MoFA-DIR-FA',
    directorate: 'F&A',
    reportsTo: 'cd-001',
    position: 'Director',
    grade: 'G10',
    level: 'Executive',
    rank: 'Director',
    step: 'Step 5',
    department: 'Finance & Administration Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2011-09-25'),
  },
  {
    userId: 'hr-fa-01',
    name: 'HR Officer F&A 1',
    firstName: 'Benjamin',
    lastName: 'Tetteh',
    email: 'hr.fa01@mofa.gov.gh',
    phone: '+233241000034',
    role: 'HR_OFFICER',
    staffId: 'MoFA-HR-FA-01',
    directorate: 'F&A',
    functional: true,
    reportsTo: 'dir-fa',
    position: 'HR Officer',
    grade: 'G6',
    level: 'Middle',
    rank: 'Principal Officer',
    step: 'Step 2',
    department: 'Finance & Administration Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2019-10-05'),
  },

  // F&A Units
  {
    userId: 'uh-fa-accounts',
    name: 'Unit Head Accounts',
    firstName: 'Richard',
    lastName: 'Asante',
    email: 'unithead.accounts@mofa.gov.gh',
    phone: '+233241000035',
    role: 'UNIT_HEAD',
    staffId: 'MoFA-UH-FA-ACCOUNTS',
    unit: 'Accounts Unit',
    directorate: 'F&A',
    reportsTo: 'dir-fa',
    position: 'Unit Head',
    grade: 'G8',
    level: 'Senior',
    rank: 'Principal Officer',
    step: 'Step 4',
    department: 'Finance & Administration Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2013-12-10'),
  },
  {
    userId: 'sup-fa-accounts-01',
    name: 'Supervisor Accounts 1',
    firstName: 'Priscilla',
    lastName: 'Mensah',
    email: 'supervisor.accounts01@mofa.gov.gh',
    phone: '+233241000036',
    role: 'SUPERVISOR',
    staffId: 'MoFA-SUP-FA-ACCOUNTS-01',
    unit: 'Accounts Unit',
    directorate: 'F&A',
    reportsTo: 'uh-fa-accounts',
    position: 'Senior Accountant',
    grade: 'G7',
    level: 'Senior',
    rank: 'Senior Officer',
    step: 'Step 3',
    department: 'Finance & Administration Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2016-07-18'),
  },
  {
    userId: 'emp-fa-accounts-01',
    name: 'Employee Accounts 1',
    firstName: 'David',
    lastName: 'Ofori',
    email: 'employee.accounts01@mofa.gov.gh',
    phone: '+233241000037',
    role: 'EMPLOYEE',
    staffId: 'MoFA-EMP-FA-ACCOUNTS-01',
    unit: 'Accounts Unit',
    directorate: 'F&A',
    reportsTo: 'sup-fa-accounts-01',
    position: 'Accountant',
    grade: 'G5',
    level: 'Junior',
    rank: 'Senior Officer',
    step: 'Step 1',
    department: 'Finance & Administration Directorate',
    dutyStation: 'HQ',
    joinDate: new Date('2022-02-15'),
  },
]

